{{- if and .Values.server.enabled .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "stellaris.server.fullname" . }}
  labels:
    {{- include "stellaris.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with (merge (deepCopy .Values.ingress.annotations) .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "stellaris.server.fullname" . }}
                port:
                  name: http
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      {{- with .Values.ingress.tls.secretName }}
      secretName: {{ . | quote }}
      {{- end }}
  {{- end }}
{{- end }}
