{{- if .Values.server.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stellaris.server.fullname" . }}
  labels:
    {{- include "stellaris.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with (merge (deepCopy .Values.server.service.annotations) .Values.commonAnnotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: http
      port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "stellaris.server.selectorLabels" . | nindent 4 }}
{{- end }}
