{{- $github := .Values.auth.github -}}
{{- if and .Values.server.enabled $github.enabled (not $github.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stellaris.github.secretName" . }}
  labels:
    {{- include "stellaris.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  client-secret: {{ $github.clientSecret | b64enc | quote }}
{{- end }}
